remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Dharnish Giri
description: Motivated and detail-oriented Robotics and Automation Engineer with hands-on experience in
industrial robot programming (KUKA, ABB, Mitsubishi) and academic expertise in ROS-based robot
control, motion planning, and path navigation. Skilled in gripping mechanisms, robot hardware
evaluation, and automation of assembly processes. Passionate about mechatronic innovation,
gripper technologies, and applying structured benchmarking frameworks. Strong teamwork,
problem-solving, and documentation abilities, with proficiency in Python, C++, ROS, and sensor integration.
